# Tasks

In [31]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Second Row : ")
print(arr[1])
print("Last Column : ")
for i in range(len(arr)):
    print(arr[i][len(arr)-1], end=" ")
print(arr[:,-1])
arr[1,1] = 0
print("Centered Value Changed : ")
print(arr)

Second Row : 
[4 5 6]
Last Column : 
3 6 9 [3 6 9]
Centered Value Changed : 
[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [32]:
import numpy as np
arr = np.arange(1,13)
print("Array : ")
arr = arr.reshape((3,4))
print(arr)
arr2 = arr[0:2, 1:3]
print(arr2)

Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [33]:
print("\n3) 5x5 array of random integers between 10 and 99:")
arr3 = np.random.randint(10, 100, size=(5, 5))
print("Random array:")
print(arr3)
print("\nRow-wise mean:")
row_means = np.mean(arr3, axis=1)
print(row_means)
print("\nColumn-wise mean:")
col_means = np.mean(arr3, axis=0)
print(col_means)
print(f"\nOverall minimum: {np.min(arr3)}")
print(f"Overall maximum: {np.max(arr3)}")


3) 5x5 array of random integers between 10 and 99:
Random array:
[[79 81 48 49 22]
 [91 23 71 15 56]
 [59 93 65 66 70]
 [57 36 74 89 20]
 [33 38 29 24 29]]

Row-wise mean:
[55.8 51.2 70.6 55.2 30.6]

Column-wise mean:
[63.8 54.2 57.4 48.6 39.4]

Overall minimum: 15
Overall maximum: 93


In [36]:
import numpy as np
marks = np.array([
    [78, 85, 90, 88],
    [92, 80, 85, 87],
    [76, 75, 70, 72],
    [88, 90, 94, 89],
    [67, 60, 65, 70]
])

print("Marks:\n", marks)

total_marks = np.sum(marks, axis=1)
print("\nTotal marks of each student:", total_marks)

avg_subject = np.mean(marks, axis=0)
print("\nAverage marks per subject:", avg_subject)

highest_index = np.argmax(total_marks)
highest_marks = total_marks[highest_index]
print(f"\nHighest scorer is Student {highest_index + 1} with {highest_marks} marks")
print("Their marks:", marks[highest_index])


Marks:
 [[78 85 90 88]
 [92 80 85 87]
 [76 75 70 72]
 [88 90 94 89]
 [67 60 65 70]]

Total marks of each student: [341 344 293 361 262]

Average marks per subject: [80.2 78.  80.8 81.2]

Highest scorer is Student 4 with 361 marks
Their marks: [88 90 94 89]


In [35]:
import numpy as np

arr = np.random.randint(1, 21, size=(3, 3))
print("3x3 Matrix with random numbers between 1 and 20:")
print(arr)

print("Sum of each row:", np.sum(arr, axis=1))
print("Sum of each column:", np.sum(arr, axis=0))


3x3 Matrix with random numbers between 1 and 20:
[[ 2 16  1]
 [20  4  7]
 [15 19 18]]
