In [2]:
import numpy as np
print(np.__version__)


2.3.1


In [3]:
lst1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lst2 = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
arr1 = np.array(lst1)
arr2 = np.array(lst2)
print(arr1 + arr2)

[11 11 11 11 11 11 11 11 11 11]


In [4]:
arr1.ndim

1

In [5]:
arr2.shape

(10,)

In [6]:
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [16]:
lst3 = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
mat1 = np.array(lst3,"float")
print(mat1)
mat1.dtype

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


dtype('float64')

In [10]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [33]:
arr = np.arange(1,10)
new_arr = arr.reshape((3, 3))
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
flat = new_arr.flatten() #----> same new_arr.ravel()
print(flat)


[1 2 3 4 5 6 7 8 9]


In [22]:
print("Before Transpose : ")
print(new_arr)
print("After Transpose : ")
print(np.transpose(new_arr))

Before Transpose : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After Transpose : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
list1 = np.array([1, 2])
list2 = np.array([3, 4])
list3 = np.concatenate((list1, list2))
print(list3)

[1 2 3 4]


In [37]:
ar = np.zeros((2, 2))
print(ar)

[[0. 0.]
 [0. 0.]]


In [41]:
ar = np.ones((2, 2))
print(ar)

[[1. 1.]
 [1. 1.]]


In [61]:
ar = np.eye(6, k=-1, dtype="int")
# np.fill_diagonal(ar, 5)
print(ar)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [58]:
ar = np.identity(5)
print(ar)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
ar = np.empty((2, 2))
print(ar)

[[1. 1.]
 [1. 1.]]


In [49]:
ar = np.full((2, 2), 12)
print(ar)

[[12 12]
 [12 12]]
